/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mobilemanagement.View;

import com.mobilemanagement.Dao.DonHangCTDAO;
import com.mobilemanagement.Dao.DonHangDAO;
import com.mobilemanagement.Dao.GiamGiaDAO;
import com.mobilemanagement.Dao.KhachHangDAO;
import com.mobilemanagement.Dao.NhanVienDAO;
import com.mobilemanagement.Model.DonHang;
import com.mobilemanagement.Model.DonHangCT;
import com.mobilemanagement.Model.GiamGia;
import com.mobilemanagement.Utility.Auth;
import com.mobilemanagement.Utility.MsgBox;
import com.mobilemanagement.Utility.XValidate;
import javax.swing.DefaultComboBoxModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DINHVU
 */
public class DonHangJPanel extends javax.swing.JPanel {

    DonHangDAO dhDao = new DonHangDAO();
    DonHangCTDAO donHangCTDAO = new DonHangCTDAO();
    DefaultTableCellRenderer tblCenter = new DefaultTableCellRenderer();

    /**
     * Creates new form DonhangJPanel
     */
    public DonHangJPanel() {
        initComponents();
        loadTable();
        
    }

    void loadTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonHang.getModel();
        model.setRowCount(0);

        tblCenter.setHorizontalAlignment(SwingConstants.CENTER); // Thiết lập căn giữa
        // Áp dụng renderer cho từng cột trong bảng
        for (int i = 0; i < tblDonHang.getColumnCount(); i++) {
            tblDonHang.getColumnModel().getColumn(i).setCellRenderer(tblCenter);

        }
        List<Object[]> list = dhDao.selectTableDonHang();
        for (Object[] row : list) {

            model.addRow(new Object[]{
                row[0], row[1], row[2], row[3], row[4], XValidate.formatCurrency(row[5]), row[6], XValidate.formatCurrency(row[7]), row[8]
            });
        }

    }

    void LoadTableDonHangCT() {
        DefaultTableModel model = (DefaultTableModel) tblDHCT.getModel();
        model.setRowCount(0);
        tblCenter.setHorizontalAlignment(SwingConstants.CENTER); // Thiết lập căn giữa
        // Áp dụng renderer cho từng cột trong bảng
        for (int i = 0; i < tblDHCT.getColumnCount(); i++) {
            tblDHCT.getColumnModel().getColumn(i).setCellRenderer(tblCenter);
                    }
        int selectedRow = tblDonHang.getSelectedRow();
        String maDH = tblDonHang.getValueAt(selectedRow, 0).toString();
        
         List<Object[]> list = donHangCTDAO.GetDonHangCTDetails(maDH);
        for (Object[] row : list) {

            model.addRow(new Object[]{
                row[0], row[1], row[2], row[3], row[4], XValidate.formatCurrency(row[5])
            });
        }
    }

    //Đổ Dữ Liệu Lên Bảng
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDHCT = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1178, 780));
        setPreferredSize(new java.awt.Dimension(1178, 780));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        tblDonHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Đơn Hàng", "Tên khách hàng", "SĐT KH", "Mã NV", "Mã Giảm Giá", "Giảm giá", "Ngày tạo ", "Tổng tiền hóa đơn", "Ghi Chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDonHang.setRowHeight(30);
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangMouseClicked(evt);
            }
        });
        tblDonHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDonHangKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblDonHang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn hàng chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        tblDHCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblDHCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ĐHCT", "Mã Đơn Hàng", "Mã Sản Phẩm", "Thông tin sản phẩm", "IEMI", "Đơn Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDHCT.setRowHeight(30);
        tblDHCT.setShowGrid(true);
        jScrollPane1.setViewportView(tblDHCT);
        if (tblDHCT.getColumnModel().getColumnCount() > 0) {
            tblDHCT.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblDHCT.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblDHCT.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDonHangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDonHangKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblDonHangKeyPressed

    private void tblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseClicked
        // TODO add your handling code here:
        LoadTableDonHangCT();
    }//GEN-LAST:event_tblDonHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDHCT;
    private javax.swing.JTable tblDonHang;
    // End of variables declaration//GEN-END:variables

}
//Phần ĐƠN HÀNG.
//----------------------------------------------------------------------------------------------------------------------------------
//PHẦN ĐƠN HÀNG CHI TIẾT

//PHẦN ĐƠN HÀNG CHI TIẾT

